server:
  port: 8085

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-postgres:5432/mecano_notif_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:0116}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Mailtrap SMTP
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME:Junior Kenfack}
    password: ${MAILTRAP_PASSWORD:23072005@ju}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

application:
  notification:
    from-email: noreply@mecano.com
    from-name: Mecano App

management:
  endpoints:
    web:
      exposure:
        include: "*"
