services:
  db-postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0116"
      POSTGRES_DB: mecano_auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  discovery-server:
    build:
      context: ./discovery-server
      network: host
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  config-server:
    build:
      context: ./config-server
      network: host
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  auth-service:
    build:
      context: ./auth-service
      network: host
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      db-postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mecano_auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0116
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  user-service:
    build:
      context: ./user-service
      network: host
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      db-postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mecano_users_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0116
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  geolocation-service:
    build:
      context: ./geolocation-service
      network: host
    container_name: geolocation-service
    ports:
      - "8083:8083"
    depends_on:
      db-postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mecano_geo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0116
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  subscription-service:
    build:
      context: ./subscription-service
      network: host
    container_name: subscription-service
    ports:
      - "8084:8084"
    depends_on:
      db-postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mecano_billing_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0116
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - STRIPE_SECRET_KEY=sk_test_REMPLACE_PAR_TA_CLE_STRIPE
      - STRIPE_WEBHOOK_SECRET=whsec_80fbbe79c88d16fbac696979bf731d07691bd2b2c376ea4f5aef91c578bc9faa

  notification-service:
    build:
      context: ./notification-service
      network: host
    container_name: notification-service
    ports:
      - "8085:8085"
    depends_on:
      db-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mecano_notif_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0116
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - MAILTRAP_USERNAME=Junior Kenfack
      - MAILTRAP_PASSWORD=23072005@ju

  repair-service:
    build:
      context: ./repair-service
      network: host
    container_name: repair-service
    ports:
      - "8086:8086"
    depends_on:
      db-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mecano_repair_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0116
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672

  messaging-service:
    build:
      context: ./messaging-service
      network: host
    container_name: messaging-service
    ports:
      - "8087:8087"
    depends_on:
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672

  admin-service:
    build:
      context: ./admin-service
      network: host
    container_name: admin-service
    ports:
      - "8088:8088"
    depends_on:
      db-postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mecano_admin_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0116
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  marketplace-service:
    build:
      context: ./marketplace-service
      network: host
    container_name: marketplace-service
    ports:
      - "8089:8089"
    depends_on:
      db-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mecano_marketplace_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0116
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672

  api-gateway:
    build:
      context: ./api-gateway
      network: host
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

volumes:
  postgres_data:
  rabbitmq_data: